// Generated by scripts/build-icons.py from design/icons/*.svg. Do not edit by hand.
import type { SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement>

// Shared root: 24x24 grid, currentColor, 1.5px round strokes (lucide-compatible props).
function Svg({ children, ...props }: IconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      {children}
    </svg>
  )
}

export function IconAiMark(props: IconProps) {
  return <Svg {...props}><path d="M12 3.5c3.5 4.5 6 7.5 6 11a6 6 0 0 1-12 0c0-3.5 2.5-6.5 6-11zM9.5 14.5a2.5 2.5 0 0 0 2.5 2.5" /></Svg>
}

export function IconAtsOptimizerActive(props: IconProps) {
  return <Svg {...props}><path d="M11 21H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v4.5M7.5 7h4M7.5 10.5h4M7.5 14h2M18.5 18l2.5 2.5" /><circle cx="16" cy="15.5" r="3.5" fill="currentColor" /></Svg>
}

export function IconAtsOptimizer(props: IconProps) {
  return <Svg {...props}><path d="M11 21H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v4.5M7.5 7h4M7.5 10.5h4M7.5 14h2M18.5 18l2.5 2.5" /><circle cx="16" cy="15.5" r="3.5" /></Svg>
}

export function IconCerts(props: IconProps) {
  return <Svg {...props}><path d="M12.5 16H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v6.5M7 8h10M7 11.5h4M14.5 17.5l-.5 3.5 2-1 2 1-.5-3.5" /><circle cx="16" cy="15.5" r="2.5" /></Svg>
}

export function IconCoverLetterActive(props: IconProps) {
  return <Svg {...props}><path fill="currentColor" fillRule="evenodd" d="M6 3h12a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2zM8 5.5h8a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-8a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5zM8 9h8a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-8a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5zM8 12.5h4a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-4a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5zM8 16h6a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-6a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5z" /></Svg>
}

export function IconCoverLetter(props: IconProps) {
  return <Svg {...props}><rect x="4" y="3" width="16" height="18" rx="2" /><path d="M8 7h8M8 10.5h8M8 14h4M8 17.75c1.25-2 2.25-2 2.75-.5s1.5 1.5 2.5 0c.5-.75 1-.75 1.5 0H16" /></Svg>
}

export function IconDashboardActive(props: IconProps) {
  return <Svg {...props}><rect x="3" y="3" width="8" height="10" rx="2" fill="currentColor" /><rect x="13" y="3" width="8" height="6" rx="2" fill="currentColor" /><rect x="13" y="11" width="8" height="10" rx="2" fill="currentColor" /><rect x="3" y="15" width="8" height="6" rx="2" fill="currentColor" /></Svg>
}

export function IconDashboard(props: IconProps) {
  return <Svg {...props}><rect x="3" y="3" width="8" height="10" rx="2" /><rect x="13" y="3" width="8" height="6" rx="2" /><rect x="13" y="11" width="8" height="10" rx="2" /><rect x="3" y="15" width="8" height="6" rx="2" /></Svg>
}

export function IconEducation(props: IconProps) {
  return <Svg {...props}><path d="M12 5 2.5 9.5 12 14l9.5-4.5zM6.5 11.6V16c0 1.4 2.5 3 5.5 3s5.5-1.6 5.5-3v-4.4M21.5 9.5v5" /></Svg>
}

export function IconError(props: IconProps) {
  return <Svg {...props}><circle cx="12" cy="12" r="9" /><path d="M9 9l6 6M15 9l-6 6" /></Svg>
}

export function IconExperience(props: IconProps) {
  return <Svg {...props}><rect x="3" y="7" width="18" height="13" rx="2" /><path d="M9 7V6a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v1M3 12.5h18" /></Svg>
}

export function IconExtra(props: IconProps) {
  return <Svg {...props}><rect x="3" y="3" width="18" height="18" rx="2" /><path d="M12 8v8M8 12h8" /></Svg>
}

export function IconInterviewPrepActive(props: IconProps) {
  return <Svg {...props}><circle cx="7" cy="8" r="2.5" fill="currentColor" /><circle cx="17" cy="8" r="2.5" fill="currentColor" /><path fill="currentColor" d="M3 17a4 4 0 0 1 8 0zM13 17a4 4 0 0 1 8 0z" /><path d="M3 20.5h18" /></Svg>
}

export function IconInterviewPrep(props: IconProps) {
  return <Svg {...props}><circle cx="7" cy="8" r="2.5" /><circle cx="17" cy="8" r="2.5" /><path d="M3 17a4 4 0 0 1 8 0M13 17a4 4 0 0 1 8 0M3 20.5h18" /></Svg>
}

export function IconJobStrategyActive(props: IconProps) {
  return <Svg {...props}><circle cx="6" cy="18" r="2" fill="currentColor" /><path d="M8 18h5a2 2 0 0 0 2-2v-3a2 2 0 0 1 2-2M17 11V3.5" /><path fill="currentColor" d="M17 3.5l4 2-4 2z" /></Svg>
}

export function IconJobStrategy(props: IconProps) {
  return <Svg {...props}><circle cx="6" cy="18" r="2" /><path d="M8 18h5a2 2 0 0 0 2-2v-3a2 2 0 0 1 2-2M17 11V3.5l4 2-4 2" /></Svg>
}

export function IconLoading(props: IconProps) {
  return <Svg {...props}><path d="M12 3.5a8.5 8.5 0 1 1-8.5 8.5" /></Svg>
}

export function IconLogoMark(props: IconProps) {
  return <Svg {...props}><path d="M12 3l6.5 11L16 20.5H8L5.5 14zM12 3v7" /><circle cx="12" cy="12.5" r="1.5" /></Svg>
}

export function IconMatched(props: IconProps) {
  return <Svg {...props}><rect className="auri-highlight" fill="currentColor" fillOpacity="0.3" stroke="none" x="2.25" y="7.25" width="19.5" height="9.5" rx="2.75" /><path d="M8.5 12l2.5 2.5 5-5" /></Svg>
}

export function IconMissing(props: IconProps) {
  return <Svg {...props}><path d="M3 11v-1a2 2 0 0 1 2-2h1.5M10.5 8h3M17.5 8H19a2 2 0 0 1 2 2v1M21 13v1a2 2 0 0 1-2 2h-1.5M13.5 16h-3M6.5 16H5a2 2 0 0 1-2-2v-1" /></Svg>
}

export function IconMyCoverLettersActive(props: IconProps) {
  return <Svg {...props}><path d="M4.5 7.5V19a2 2 0 0 0 2 2H15" /><path fill="currentColor" fillRule="evenodd" d="M9.5 3h8a2 2 0 0 1 2 2v11a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2zM10.5 5.5h6a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-6a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5zM10.5 9h6a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-6a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5zM10.5 12.75h3.5a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-3.5a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5z" /></Svg>
}

export function IconMyCoverLetters(props: IconProps) {
  return <Svg {...props}><path d="M4.5 7.5V19a2 2 0 0 0 2 2H15" /><rect x="7.5" y="3" width="12" height="15" rx="2" /><path d="M10.5 7h6M10.5 10.5h6M10.5 14.5c.8-1.3 1.6-1.3 2 0s1.2 1.3 2 0c.4-.6.8-.6 1.2 0h.8" /></Svg>
}

export function IconMyResumesActive(props: IconProps) {
  return <Svg {...props}><path d="M4.5 7.5V19a2 2 0 0 0 2 2H15" /><path fill="currentColor" fillRule="evenodd" d="M9.5 3h8a2 2 0 0 1 2 2v11a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2zM9 7.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0zM10.5 10.25h6a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-6a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5zM10.5 13.75h3.5a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-3.5a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5z" /></Svg>
}

export function IconMyResumes(props: IconProps) {
  return <Svg {...props}><path d="M4.5 7.5V19a2 2 0 0 0 2 2H15" /><rect x="7.5" y="3" width="12" height="15" rx="2" /><circle cx="11.5" cy="7.5" r="1.75" /><path d="M10.5 11.75h6M10.5 15.25h3.5" /></Svg>
}

export function IconMyStrategiesActive(props: IconProps) {
  return <Svg {...props}><path d="M4.5 7.5V19a2 2 0 0 0 2 2H15" /><path fill="currentColor" fillRule="evenodd" d="M9.5 3h8a2 2 0 0 1 2 2v11a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2zM11 5h0a1.5 1.5 0 0 1 1.5 1.5v8.5a1.5 1.5 0 0 1 -1.5 1.5h-0a1.5 1.5 0 0 1 -1.5 -1.5v-8.5a1.5 1.5 0 0 1 1.5 -1.5zM12.5 5.9 17.6 9l-5.1 3.1z" /></Svg>
}

export function IconMyStrategies(props: IconProps) {
  return <Svg {...props}><path d="M4.5 7.5V19a2 2 0 0 0 2 2H15" /><rect x="7.5" y="3" width="12" height="15" rx="2" /><path d="M11 15V6.5l5 2.5-5 2.5" /></Svg>
}

export function IconNeedsCheck(props: IconProps) {
  return <Svg {...props}><path d="M3 12c2-4 5.5-6 9-6s7 2 9 6c-2 4-5.5 6-9 6s-7-2-9-6z" /><circle cx="12" cy="12" r="2.5" /></Svg>
}

export function IconOffline(props: IconProps) {
  return <Svg {...props}><path d="M4.5 12a7.5 7.5 0 0 1 13-5.1M19.5 12a7.5 7.5 0 0 1-13 5.1M4 4l16 16" /></Svg>
}

export function IconPartial(props: IconProps) {
  return <Svg {...props}><path d="M12 8H5a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h7M15.5 8H19a2 2 0 0 1 2 2v1M21 13v1a2 2 0 0 1-2 2h-3.5M7.5 12h3" /></Svg>
}

export function IconPersonal(props: IconProps) {
  return <Svg {...props}><circle cx="12" cy="8" r="3.5" /><path d="M5 20a7 7 0 0 1 14 0" /></Svg>
}

export function IconProBadge(props: IconProps) {
  return <Svg {...props}><circle cx="12" cy="9" r="6" /><path d="M8.5 13.9 7.5 21l4.5-2.5 4.5 2.5-1-7.1M12 6.5l2 2.5-2 2.5-2-2.5z" /></Svg>
}

export function IconProfileRewriterActive(props: IconProps) {
  return <Svg {...props}><path fill="currentColor" fillRule="evenodd" d="M5 3h10a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-6a2 2 0 0 1 2 -2zM4.25 8a2.75 2.75 0 1 0 5.5 0a2.75 2.75 0 1 0 -5.5 0zM11.5 5h2.5a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-2.5a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5zM11.5 8.5h2.5a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-2.5a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5z" /><path fill="currentColor" d="M19.5 11.7l1.8 1.8-5.4 5.4L12 21l2.1-3.9z" /></Svg>
}

export function IconProfileRewriter(props: IconProps) {
  return <Svg {...props}><rect x="3" y="3" width="14" height="10" rx="2" /><circle cx="7" cy="8" r="2" /><path d="M11.5 6.5h2.5M11.5 10h2.5M19.5 11.7l1.8 1.8-5.4 5.4L12 21l2.1-3.9zM12 21l1.8-1.8" /></Svg>
}

export function IconProjects(props: IconProps) {
  return <Svg {...props}><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h8a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" /></Svg>
}

export function IconResumeBuilderActive(props: IconProps) {
  return <Svg {...props}><path fill="currentColor" fillRule="evenodd" d="M7 3h10a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2zM6.5 8a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0zM13.5 5.5h2.5a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-2.5a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5zM13.5 9h2.5a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-2.5a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5zM8.5 12.5h7a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-7a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5zM8.5 16h7a1.5 1.5 0 0 1 1.5 1.5v0a1.5 1.5 0 0 1 -1.5 1.5h-7a1.5 1.5 0 0 1 -1.5 -1.5v-0a1.5 1.5 0 0 1 1.5 -1.5z" /></Svg>
}

export function IconResumeBuilder(props: IconProps) {
  return <Svg {...props}><rect x="5" y="3" width="14" height="18" rx="2" /><circle cx="9" cy="8" r="1.75" /><path d="M13.5 7h2.5M13.5 10.5h2.5M8.5 14h7M8.5 17.5h7" /></Svg>
}

export function IconSettingsActive(props: IconProps) {
  return <Svg {...props}><path d="M4 7h8M16 7h4M4 17h4M12 17h8" /><circle cx="14" cy="7" r="2" fill="currentColor" /><circle cx="10" cy="17" r="2" fill="currentColor" /></Svg>
}

export function IconSettings(props: IconProps) {
  return <Svg {...props}><path d="M4 7h8M16 7h4M4 17h4M12 17h8" /><circle cx="14" cy="7" r="2" /><circle cx="10" cy="17" r="2" /></Svg>
}

export function IconSkills(props: IconProps) {
  return <Svg {...props}><rect x="3" y="8" width="18" height="8" rx="2" /><path d="M7 8v3M10.5 8v2M14 8v3M17.5 8v2" /></Svg>
}

export function IconSynced(props: IconProps) {
  return <Svg {...props}><path d="M4.5 12a7.5 7.5 0 0 1 13-5.1M17.5 3.7v3.2h-3.2M19.5 12a7.5 7.5 0 0 1-13 5.1M6.5 20.3v-3.2h3.2M9.5 12l1.75 1.75L14.5 10.5" /></Svg>
}

export function IconTargetJob(props: IconProps) {
  return <Svg {...props}><circle cx="12" cy="12" r="8.5" /><circle cx="12" cy="12" r="5" /><path d="M12 12v.01" /></Svg>
}

export function IconTip(props: IconProps) {
  return <Svg {...props}><path d="M4 5a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v9l-6 7H6a2 2 0 0 1-2-2zM14 21v-5a2 2 0 0 1 2-2h4M8 8h8M8 11.5h4" /></Svg>
}

export function IconWarning(props: IconProps) {
  return <Svg {...props}><path d="M11.02 5.24Q12 3.5 12.98 5.24L20.02 17.76Q21 19.5 19 19.5H5Q3 19.5 3.98 17.76zM12 9.5V14M12 16.75v.01" /></Svg>
}
