"""Generate components/icons/index.tsx from design/icons/*.svg.

Run: python3 scripts/build-icons.py
Source SVGs come from Claude Design (24x24, currentColor, 1.5px stroke).
Their C2PA provenance metadata stays in design/icons; it is not copied
into the components.
"""
import pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'design' / 'icons'
OUT = ROOT / 'components' / 'icons' / 'index.tsx'

ATTR = {'class': 'className', 'fill-opacity': 'fillOpacity', 'stroke-width': 'strokeWidth',
        'stroke-linecap': 'strokeLinecap', 'stroke-linejoin': 'strokeLinejoin',
        'fill-rule': 'fillRule', 'clip-rule': 'clipRule', 'stroke-opacity': 'strokeOpacity'}

def pascal(name):
    return 'Icon' + ''.join(p.capitalize() for p in name.split('-'))

def jsx(body):
    body = re.sub(r'<(\w+)([^>]*)></\1>', r'<\1\2 />', body)
    for k, v in ATTR.items():
        body = re.sub(r'\b' + k + '=', v + '=', body)
    return body

parts = []
for f in sorted(SRC.glob('*.svg')):
    if f.stem == 'favicon':
        continue
    s = f.read_text()
    s = re.sub(r'<metadata>.*?</metadata>', '', s, flags=re.S)
    body = re.sub(r'^.*?<svg[^>]*>', '', s, flags=re.S).replace('</svg>', '').strip()
    parts.append(f"export function {pascal(f.stem)}(props: IconProps) {{\n  return <Svg {{...props}}>{jsx(body)}</Svg>\n}}\n")

header = '''// Generated by scripts/build-icons.py from design/icons/*.svg. Do not edit by hand.
import type { SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement>

// Shared root: 24x24 grid, currentColor, 1.5px round strokes (lucide-compatible props).
function Svg({ children, ...props }: IconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      {children}
    </svg>
  )
}

'''
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(header + '\n'.join(parts))
print('wrote', OUT, len(parts), 'icons')
